import {
  alternateCase1,
  alternateCase2,
  camelCase,
  constantCase,
  dotCase,
  invertCase,
  kebabCase,
  lowerCase,
  noCase,
  pascalCase,
  pathCase,
  snakeCase,
  reverseTitleCase,
  sentenceCase,
  spongeCase as randomCase,
  titleCase,
  toggleCase,
  trainCase,
  upperCase,
} from "case-string";

const tools = [
  {
    id: "uppercase",
    kind: "dropdown",
    menuName: "Change Case",
    optionName: "Uppercase",
    title: "Convert to Uppercase",
    optionDescription: "This option converts the given text to uppercase.",
    route: "/uppercase",
    order: 10,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => upperCase(inputText),
  },
  {
    id: "lowercase",
    kind: "dropdown",
    menuName: "Change Case",
    optionName: "Lowercase",
    title: "Convert to Lowercase",
    optionDescription: "This option converts the given text to lowercase.",
    route: "/lowercase",
    order: 20,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => lowerCase(inputText),
  },
  {
    id: "titlecase",
    kind: "dropdown",
    menuName: "Change Case",
    optionName: "Titlecase",
    title: "Convert to Titlecase",
    optionDescription: "This option converts the given text to titlecase.",
    route: "/title-case",
    order: 30,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => titleCase(inputText),
  },
  {
    id: "reverseTitleCase",
    kind: "dropdown",
    menuName: "Change Case",
    optionName: "Reverse Titlecase",
    title: "Convert to Reverse Titlecase",
    optionDescription:
      "This option converts the given text to reverse titlecase.",
    order: 40,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => reverseTitleCase(inputText),
  },
  {
    id: "invertcase",
    kind: "dropdown",
    menuName: "Change Case",
    optionName: "Invert Case",
    title: "Convert to Invert Case",
    optionDescription: "This option converts the given text to invert case.",
    order: 50,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => invertCase(inputText),
  },
  {
    id: "sentencecase",
    kind: "dropdown",
    menuName: "Change Case",
    optionName: "Sentence Case",
    title: "Convert to Sentence Case",
    optionDescription: "This option converts the given text to sentence case.",
    route: "/sentence-case",
    order: 60,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => sentenceCase(inputText),
  },
  {
    id: "togglecase",
    kind: "dropdown",
    menuName: "Change Case",
    optionName: "Toggle Case",
    title: "Convert to Toggle Case",
    optionDescription: "This option converts the given text to toggle case.",
    order: 70,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => toggleCase(inputText),
  },
  {
    id: "randomcase",
    kind: "dropdown",
    menuName: "Change Case",
    optionName: "Random Case",
    title: "Convert to Random Case",
    optionDescription: "This option converts the given text to random case.",
    order: 80,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => randomCase(inputText),
  },
  {
    id: "camelcase",
    kind: "dropdown",
    menuName: "Change Case",
    optionName: "Camel Case",
    title: "Convert to Camel Case",
    optionDescription: "This option converts the given text to camel case.",
    route: "/camel-case",
    order: 90,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => camelCase(inputText),
  },
  {
    id: "pascalcase",
    kind: "dropdown",
    menuName: "Change Case",
    optionName: "Pascal Case",
    title: "Convert to Pascal Case",
    optionDescription: "This option converts the given text to pascal case.",
    order: 100,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => pascalCase(inputText),
  },
  {
    id: "kebabcase",
    kind: "dropdown",
    menuName: "Change Case",
    optionName: "Kebab Case",
    title: "Convert to Kebab Case",
    optionDescription: "This option converts the given text to kebab case.",
    order: 110,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => kebabCase(inputText),
  },
  {
    id: "snakecase",
    kind: "dropdown",
    menuName: "Change Case",
    optionName: "Snake Case",
    title: "Convert to Snake Case",
    optionDescription: "This option converts the given text to snake case.",
    order: 120,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => snakeCase(inputText),
  },
  {
    id: "constantcase",
    kind: "dropdown",
    menuName: "Change Case",
    optionName: "Constant Case",
    title: "Convert to Constant Case",
    optionDescription: "This option converts the given text to constant case.",
    order: 130,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => constantCase(inputText),
  },
  {
    id: "dotcase",
    kind: "dropdown",
    menuName: "Change Case",
    optionName: "Dot Case",
    title: "Convert to Dot Case",
    optionDescription: "This option converts the given text to dot case.",
    order: 140,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => dotCase(inputText),
  },
  {
    id: "nocase",
    kind: "dropdown",
    menuName: "Change Case",
    optionName: "No Case",
    title: "Convert to No Case",
    optionDescription: "This option converts the given text to no case.",
    order: 150,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => noCase(inputText),
  },
  {
    id: "alternatecase1",
    kind: "dropdown",
    menuName: "Change Case",
    optionName: "Alternate Case 1",
    title: "Convert to Alternate Case 1",
    optionDescription:
      "This option converts the given text to alternate case 1.",
    order: 160,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => alternateCase1(inputText),
  },
  {
    id: "pathcase",
    kind: "dropdown",
    menuName: "Change Case",
    optionName: "Path Case",
    title: "Convert to Path Case",
    optionDescription: "This option converts the given text to path case.",
    order: 170,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => pathCase(inputText),
  },
  {
    id: "traincase",
    kind: "dropdown",
    menuName: "Change Case",
    optionName: "Train Case",
    title: "Convert to Train Case",
    optionDescription: "This option converts the given text to train case.",
    order: 180,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => trainCase(inputText),
  },
  {
    id: "alternatecase2",
    kind: "dropdown",
    menuName: "Change Case",
    optionName: "Alternate Case 2",
    title: "Convert to Alternate Case 2",
    optionDescription:
      "This option converts the given text to alternate case 2.",
    order: 190,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => alternateCase2(inputText),
  },
];

export default tools;
