import { frequencyOfString } from "character-frequency";
import wordsFrequency from "words-frequency";
import {
  splitString,
  joinString,
  removeExtraSpaces,
  removeAllSpaces,
  removeAllSymbols,
  duplicate,
  reverse,
  slugify,
  truncate,
  paraToSingleLine,
  alphabetize,
  zalgo,
  rotate13Deg,
  encodeUri,
  decodeUri,
  base64Enode,
  base64Decode,
  addPrefix,
  addSuffix,
  extractText,
} from "superbstring";
import {
  decimalToRoman,
  extractNumber,
  formatNumbers,
  romanToDecimal,
  unixToDate,
  unixToTime,
} from "number-pro";
import { addLineNumbers } from "../../../../utils/text/addLineNumbers";
import {
  sortLinesCaseInsensitive,
  sortLinesCaseSensitive,
  sortLinesReverseCaseInsensitive,
  sortLinesReverseCaseSensitive,
} from "../../../../utils/text/sortLines";
import { convertToHashCode } from "../../../../utils/text/convertToHashCode";

function charFreqStr(text) {
  const json = frequencyOfString(text);
  return Object.entries(json)
    .map(([key, value]) => `${key} = ${value}`)
    .join("\n");
}

function wordFreq(text) {
  const json = wordsFrequency(text).data;
  return Object.entries(json)
    .map(([key, value]) => `${key} = ${value}`)
    .join("\n");
}

const tools = [
  {
    id: "splitInput",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Split Text",
    title: "Split all words to new lines.",
    optionDescription:
      "This option splits each word of the given text on a new line.",
    order: 10,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => splitString(inputText),
  },
  {
    id: "joinInput",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Join Text",
    title: "Join all the text to a single line.",
    optionDescription:
      "This option joins all of the words in separate lines to a single string.",
    order: 20,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => joinString(inputText),
  },
  {
    id: "removeExtraSpaces",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Remove Extra Spaces",
    title: "Removes extra spaces, new lines, tab spaces",
    optionDescription: "This option removes any extra space present in the text.",
    order: 30,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => removeExtraSpaces(inputText),
  },
  {
    id: "removeAllSpaces",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Remove All Spaces",
    title: "Removes all the spaces, new lines, tab spaces",
    optionDescription: "This option removes all the spaces, new lines, tab spaces.",
    order: 40,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => removeAllSpaces(inputText),
  },
  {
    id: "removeAllSymbols",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Remove All Symbols",
    title: "Removes all the symbols",
    optionDescription: "This option removes all the symbols.",
    order: 50,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => removeAllSymbols(inputText),
  },
  {
    id: "duplicate",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Duplicate",
    title: "Duplicate text",
    optionDescription: "This option duplicates the given text.",
    order: 60,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }, runtime) => {
      const count = runtime.prompt("Enter duplicate count:");
      return duplicate(inputText, count);
    },
  },
  {
    id: "reverse",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Reverse",
    title: "Reverse text",
    optionDescription: "This option reverses the given text.",
    order: 70,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => reverse(inputText),
  },
  {
    id: "slugify",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Slugify",
    title: "Slugify text",
    optionDescription: "This option converts the given text to a slug.",
    order: 80,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => slugify(inputText),
  },
  {
    id: "truncate",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Truncate",
    title: "Truncate the text up to desired length",
    optionDescription:
      "This option truncates the given text up to the desired length.",
    order: 90,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }, runtime) => {
      const length = runtime.prompt("Enter truncation length:");
      return truncate(inputText, length);
    },
  },
  {
    id: "paragraphToSingleLine",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Paragraph to single line",
    title: "Convert paragraphs to single line",
    optionDescription: "This option converts paragraphs to a single line.",
    order: 100,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => paraToSingleLine(inputText),
  },
  {
    id: "alphabetize",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Alphabetize Text",
    title: "Change the order of words in text as A-Z",
    optionDescription:
      "This option changes the order of words in the given text as A-Z.",
    order: 110,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => alphabetize(inputText),
  },
  {
    id: "zalgo",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Zalgo",
    title: "Apply Zalgo effect",
    optionDescription: "This option applies the Zalgo effect to the given text.",
    order: 120,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => zalgo(inputText),
  },
  {
    id: "rotate13",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Rotate 13",
    title: "Rotate 13 decoder",
    optionDescription: "This option rotates the given text by 13 places.",
    order: 130,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => rotate13Deg(inputText),
  },
  {
    id: "addLineNum",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Add Line Number",
    title: "Add line number to each line",
    optionDescription: "This option adds line number to each line of the given text.",
    order: 140,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => addLineNumbers(inputText),
  },
  {
    id: "encodeUri",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Encode URL",
    title: "Encode to URL",
    optionDescription: "This option encodes the given text to a URL.",
    order: 150,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => encodeUri(inputText),
  },
  {
    id: "decodeUri",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Decode the URL",
    title: "Decode the URL",
    optionDescription: "This option decodes the given URL.",
    order: 160,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => decodeUri(inputText),
  },
  {
    id: "base64Encode",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Base64 Encode",
    title: "Encode to Base64",
    optionDescription: "This option encodes the given text to Base64.",
    order: 170,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => base64Enode(inputText),
  },
  {
    id: "base64Decode",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Base64 Decode",
    title: "Decode the Base64",
    optionDescription: "This option decodes the given Base64 text.",
    order: 180,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => base64Decode(inputText),
  },
  {
    id: "unixToDate",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "UNIX to Date",
    title: "Convert from Unix to date",
    optionDescription:
      "This option converts the given Unix timestamp to a date.",
    order: 190,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => unixToDate(inputText),
  },
  {
    id: "unixToTime",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "UNIX to Time",
    title: "Convert from Unix to time",
    optionDescription:
      "This option converts the given Unix timestamp to a time.",
    order: 200,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => unixToTime(inputText),
  },
  {
    id: "formatNumbers",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Format Numbers",
    title: "Adds comma to numbers after every three digits",
    optionDescription:
      "This option adds a comma to numbers after every three digits.",
    order: 210,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => formatNumbers(inputText),
  },
  {
    id: "extractText",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Extract Text",
    title: "Extract the text from the given string",
    optionDescription:
      "This option extracts the text from the given string.",
    order: 220,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => extractText(inputText),
  },
  {
    id: "extractNumbers",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Extract Numbers",
    title: "Extract the numbers from the given string",
    optionDescription:
      "This option extracts the numbers from the given string.",
    order: 230,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => extractNumber(inputText),
  },
  {
    id: "addPrefix",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Add Prefix",
    title: "Add prefix to each line",
    optionDescription: "This option adds a prefix to each line of the given text.",
    order: 240,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }, runtime) => {
      const prefix = runtime.prompt("Enter the prefix:");
      return addPrefix(inputText, prefix);
    },
  },
  {
    id: "addSuffix",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Add Suffix",
    title: "Add suffix to each line",
    optionDescription: "This option adds a suffix to each line of the given text.",
    order: 250,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }, runtime) => {
      const suffix = runtime.prompt("Enter the suffix:");
      return addSuffix(inputText, suffix);
    },
  },
  {
    id: "sortLinesSENS",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Sort Lines SENS",
    title: "Sort lines in the alphabetical order",
    optionDescription:
      "This option sorts the lines of the given text in alphabetical order.",
    order: 260,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => sortLinesCaseSensitive(inputText),
  },
  {
    id: "sortLinesINSENS",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Sort Lines INSENS",
    title: "Sort lines in the alphabetical order (case insensitive)",
    optionDescription:
      "This option sorts the lines of the given text in alphabetical order.",
    order: 270,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => sortLinesCaseInsensitive(inputText),
  },
  {
    id: "sortLinesReverseSENS",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Sort Lines Reverse SENS",
    title: "Sort lines in the reverse alphabetical order",
    optionDescription:
      "This option sorts the lines of the given text in reverse alphabetical order.",
    order: 280,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => sortLinesReverseCaseSensitive(inputText),
  },
  {
    id: "sortLinesReverseINSENS",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Sort Lines Reverse INSENS",
    title: "Sort lines in the reverse alphabetical order (case insensitive)",
    optionDescription:
      "This option sorts the lines of the given text in reverse alphabetical order.",
    order: 290,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => sortLinesReverseCaseInsensitive(inputText),
  },
  {
    id: "convertDecimalToRoman",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Convert Decimal to Roman",
    title: "Converts Decimal to Roman numbers.",
    optionDescription:
      "This option converts the given decimal number to a Roman numeral.",
    order: 300,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => decimalToRoman(inputText),
  },
  {
    id: "convertRomanToDecimal",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Convert Roman to Decimal",
    title: "Converts Roman numbers to Decimal.",
    optionDescription:
      "This option converts the given Roman numeral to a decimal number.",
    order: 310,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => romanToDecimal(inputText),
  },
  {
    id: "convertToHashCode",
    kind: "dropdown",
    menuName: "Edit",
    optionName: "Convert to Hash Code",
    title: "Convert to Hash Code.",
    optionDescription: "This option converts the given text to a hash code.",
    order: 320,
    requiresInput: true,
    applyTo: "outputOnly",
    transitions: { output: true },
    execute: ({ inputText }) => convertToHashCode(inputText),
  },
  {
    id: "charFreqStr",
    kind: "dropdown",
    menuName: "Generate",
    optionName: "Generate Characters Frequency",
    title: "Generate characters frequency",
    optionDescription:
      "This option generates the frequency of characters in the given text.",
    order: 10,
    requiresInput: false,
    applyTo: "both",
    transitions: { output: true },
    execute: ({ inputText }) => charFreqStr(inputText),
  },
  {
    id: "wordFreq",
    kind: "dropdown",
    menuName: "Generate",
    optionName: "Generate Words Frequency",
    title: "Generate words frequency",
    optionDescription:
      "This option generates the frequency of words in the given text.",
    order: 20,
    requiresInput: false,
    applyTo: "both",
    transitions: { output: true },
    execute: ({ inputText }) => wordFreq(inputText),
  },
];

export default tools;
